[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=6.2", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "openbind_initial_refinement"
authors = [{name = "Conor F Wild", email = "c.wild@diamond.ac.uk"}]
dynamic = ["version"]
dependencies = [
    "numpy",
    "scipy",
    "joblib",
    'gemmi'
 ]
license.file = "LICENSE"
readme = "README.md"
requires-python = ">=3.9"